name: ghh-runner

on:
  push:
    branches:
      - main

jobs:
  ngrok_tunnel:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.test.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          # Add any additional configurations or SSH setup steps here

      - name: Start NGROK tunnel
        run: |
          docker run --net=host -e NGROK_AUTHTOKEN=${{ secrets.test.NGROK_AUTHTOKEN }} ngrok/ngrok:latest tcp 22
